/*
 * Created on 7 Mar 2016 ( Time 11:04:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

import org.hibernate.envers.Audited;

/**
 * Persistent class for entity stored in table "admin_user_group"
 *
 * @author Telosys Tools Generator
 *
 */




@Audited
@Entity
// Define named queries here
@Table(name = "admin_user_group")
@org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class AdminUserGroup extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
//	@EmbeddedId
//   private AdminUserGroupKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", nullable=false, length=30)
    private String     name         ;    @Column(name="description", length=50)
    private String     description  ;    @Column(name="editing_timeout")
    private Short      editingTimeout ;    @Column(name="editing_limit", length=10)
    private String     editingLimit ;    @Column(name="has_edit_dif_date")
    private Boolean    hasEditDifDate ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="adminUserGroup", targetEntity=AdminUser.class)
    private List<AdminUser> listOfAdminUser;

    @OneToMany(mappedBy="adminUserGroup", targetEntity=AdminUserGivenRole.class)
    private List<AdminUserGivenRole> listOfAdminUserGivenRole;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------



    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }




    //--- DATABASE MAPPING : description ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }




    //--- DATABASE MAPPING : editing_timeout ( SMALLINT ) 
    public void setEditingTimeout( Short editingTimeout ) {
        this.editingTimeout = editingTimeout;
    }
    public Short getEditingTimeout() {
        return this.editingTimeout;
    }




    //--- DATABASE MAPPING : editing_limit ( VARCHAR ) 
    public void setEditingLimit( String editingLimit ) {
        this.editingLimit = editingLimit;
    }
    public String getEditingLimit() {
        return this.editingLimit;
    }




    //--- DATABASE MAPPING : has_edit_dif_date ( BIT ) 
    public void setHasEditDifDate( Boolean hasEditDifDate ) {
        this.hasEditDifDate = hasEditDifDate;
    }
    public Boolean getHasEditDifDate() {
        return this.hasEditDifDate;
    }





    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfAdminUser( List<AdminUser> listOfAdminUser ) {
        this.listOfAdminUser = listOfAdminUser;
    }
    public List<AdminUser> getListOfAdminUser() {
        return this.listOfAdminUser;
    }

    public void setListOfAdminUserGivenRole( List<AdminUserGivenRole> listOfAdminUserGivenRole ) {
        this.listOfAdminUserGivenRole = listOfAdminUserGivenRole;
    }
    public List<AdminUserGivenRole> getListOfAdminUserGivenRole() {
        return this.listOfAdminUserGivenRole;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(editingTimeout);
        sb.append("|");
        sb.append(editingLimit);
        sb.append("|");
        sb.append(hasEditDifDate);
        sb.append("|");
        sb.append(version);
        return sb.toString(); 
    } 

}
