/*
 * Created on 7 Mar 2016 ( Time 11:04:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

import org.hibernate.envers.Audited;

/**
 * Persistent class for entity stored in table "bank"
 *
 * @author Telosys Tools Generator
 *
 */




@Audited
@Entity
// Define named queries here
@Table(name = "bank")
@org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Bank extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
//	@EmbeddedId
//   private BankKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="account_no", nullable=false, length=15)
    private String     accountNo    ;    @Column(name="name", nullable=false, length=50)
    private String     name         ;    @Column(name="branch", length=30)
    private String     branch       ;    @Column(name="city", length=20)
    private String     city         ;    @Column(name="iban", length=26)
    private String     iban         ;    @Column(name="exc_code", length=3)
    private String     excCode      ;    @Column(name="insert_by", length=20)
    private String     insertBy     ;    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="insert_at")
    private Date       insertAt     ;    @Column(name="update_by", length=20)
    private String     updateBy     ;    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_at")
    private Date       updateAt     ;    @Column(name="is_active")
    private Boolean    isActive     ;    @Column(name="workspace", nullable=false)
    private Integer    workspace    ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="bank", targetEntity=ChqbllDetailHistory.class)
    private List<ChqbllDetailHistory> listOfChqbllDetailHistory;

    @OneToMany(mappedBy="bank", targetEntity=ChqbllTrans.class)
    private List<ChqbllTrans> listOfChqbllTrans;

    @OneToMany(mappedBy="bank", targetEntity=BankTrans.class)
    private List<BankTrans> listOfBankTrans;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------



    //--- DATABASE MAPPING : account_no ( VARCHAR ) 
    public void setAccountNo( String accountNo ) {
        this.accountNo = accountNo;
    }
    public String getAccountNo() {
        return this.accountNo;
    }




    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }




    //--- DATABASE MAPPING : branch ( VARCHAR ) 
    public void setBranch( String branch ) {
        this.branch = branch;
    }
    public String getBranch() {
        return this.branch;
    }




    //--- DATABASE MAPPING : city ( VARCHAR ) 
    public void setCity( String city ) {
        this.city = city;
    }
    public String getCity() {
        return this.city;
    }




    //--- DATABASE MAPPING : iban ( VARCHAR ) 
    public void setIban( String iban ) {
        this.iban = iban;
    }
    public String getIban() {
        return this.iban;
    }




    //--- DATABASE MAPPING : exc_code ( VARCHAR ) 
    public void setExcCode( String excCode ) {
        this.excCode = excCode;
    }
    public String getExcCode() {
        return this.excCode;
    }




    //--- DATABASE MAPPING : insert_by ( VARCHAR ) 
    public void setInsertBy( String insertBy ) {
        this.insertBy = insertBy;
    }
    public String getInsertBy() {
        return this.insertBy;
    }




    //--- DATABASE MAPPING : insert_at ( DATETIME ) 
    public void setInsertAt( Date insertAt ) {
        this.insertAt = insertAt;
    }
    public Date getInsertAt() {
        return this.insertAt;
    }




    //--- DATABASE MAPPING : update_by ( VARCHAR ) 
    public void setUpdateBy( String updateBy ) {
        this.updateBy = updateBy;
    }
    public String getUpdateBy() {
        return this.updateBy;
    }




    //--- DATABASE MAPPING : update_at ( DATETIME ) 
    public void setUpdateAt( Date updateAt ) {
        this.updateAt = updateAt;
    }
    public Date getUpdateAt() {
        return this.updateAt;
    }




    //--- DATABASE MAPPING : is_active ( BIT ) 
    public void setIsActive( Boolean isActive ) {
        this.isActive = isActive;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }




    //--- DATABASE MAPPING : workspace ( INT ) 
    public void setWorkspace( Integer workspace ) {
        this.workspace = workspace;
    }
    public Integer getWorkspace() {
        return this.workspace;
    }





    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfChqbllDetailHistory( List<ChqbllDetailHistory> listOfChqbllDetailHistory ) {
        this.listOfChqbllDetailHistory = listOfChqbllDetailHistory;
    }
    public List<ChqbllDetailHistory> getListOfChqbllDetailHistory() {
        return this.listOfChqbllDetailHistory;
    }

    public void setListOfChqbllTrans( List<ChqbllTrans> listOfChqbllTrans ) {
        this.listOfChqbllTrans = listOfChqbllTrans;
    }
    public List<ChqbllTrans> getListOfChqbllTrans() {
        return this.listOfChqbllTrans;
    }

    public void setListOfBankTrans( List<BankTrans> listOfBankTrans ) {
        this.listOfBankTrans = listOfBankTrans;
    }
    public List<BankTrans> getListOfBankTrans() {
        return this.listOfBankTrans;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(accountNo);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(branch);
        sb.append("|");
        sb.append(city);
        sb.append("|");
        sb.append(iban);
        sb.append("|");
        sb.append(excCode);
        sb.append("|");
        sb.append(insertBy);
        sb.append("|");
        sb.append(insertAt);
        sb.append("|");
        sb.append(updateBy);
        sb.append("|");
        sb.append(updateAt);
        sb.append("|");
        sb.append(isActive);
        sb.append("|");
        sb.append(workspace);
        sb.append("|");
        sb.append(version);
        return sb.toString(); 
    } 

}
