/*
 * Created on 7 Mar 2016 ( Time 11:04:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

import org.hibernate.envers.Audited;

/**
 * Persistent class for entity stored in table "invoice_trans_relation"
 *
 * @author Telosys Tools Generator
 *
 */




@Audited
@Entity
// Define named queries here
@Table(name = "invoice_trans_relation")
@org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class InvoiceTransRelation extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
//	@EmbeddedId
//   private InvoiceTransRelationKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="rel_id", nullable=false)
    private Integer    relId        ;    @Column(name="rel_right", nullable=false, length=30)
    private String     relRight     ;    @Column(name="rel_receipt_no", nullable=false)
    private Integer    relReceiptNo ;
	// "transId" (column "trans_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="trans_id", referencedColumnName="id")
    private InvoiceTrans invoiceTrans;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------



    //--- DATABASE MAPPING : rel_id ( INT ) 
    public void setRelId( Integer relId ) {
        this.relId = relId;
    }
    public Integer getRelId() {
        return this.relId;
    }




    //--- DATABASE MAPPING : rel_right ( VARCHAR ) 
    public void setRelRight( String relRight ) {
        this.relRight = relRight;
    }
    public String getRelRight() {
        return this.relRight;
    }




    //--- DATABASE MAPPING : rel_receipt_no ( INT ) 
    public void setRelReceiptNo( Integer relReceiptNo ) {
        this.relReceiptNo = relReceiptNo;
    }
    public Integer getRelReceiptNo() {
        return this.relReceiptNo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setInvoiceTrans( InvoiceTrans invoiceTrans ) {
        this.invoiceTrans = invoiceTrans;
    }
    public InvoiceTrans getInvoiceTrans() {
        return this.invoiceTrans;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(relId);
        sb.append("|");
        sb.append(relRight);
        sb.append("|");
        sb.append(relReceiptNo);
        return sb.toString(); 
    } 

}
