/*
 * Created on 7 Mar 2016 ( Time 11:04:58 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

import org.hibernate.envers.Audited;

/**
 * Persistent class for entity stored in table "sale_seller"
 *
 * @author Telosys Tools Generator
 *
 */




@Audited
@Entity
// Define named queries here
@Table(name = "sale_seller")
@org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class SaleSeller extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
//	@EmbeddedId
//   private SaleSellerKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", nullable=false, length=30)
    private String     name         ;    @Column(name="prim_rate", nullable=false)
    private Double     primRate     ;    @Column(name="insert_by", length=20)
    private String     insertBy     ;    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="insert_at")
    private Date       insertAt     ;    @Column(name="update_by", length=20)
    private String     updateBy     ;    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_at")
    private Date       updateAt     ;    @Column(name="is_active")
    private Boolean    isActive     ;    @Column(name="workspace", nullable=false)
    private Integer    workspace    ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="saleSeller", targetEntity=StockTransDetail.class)
    private List<StockTransDetail> listOfStockTransDetail;

    @OneToMany(mappedBy="saleSeller", targetEntity=StockTrans.class)
    private List<StockTrans> listOfStockTrans;

    @OneToMany(mappedBy="saleSeller", targetEntity=WaybillTrans.class)
    private List<WaybillTrans> listOfWaybillTrans;

    @OneToMany(mappedBy="saleSeller", targetEntity=InvoiceTransDetail.class)
    private List<InvoiceTransDetail> listOfInvoiceTransDetail;

    @OneToMany(mappedBy="saleSeller", targetEntity=WaybillTransDetail.class)
    private List<WaybillTransDetail> listOfWaybillTransDetail;

    @OneToMany(mappedBy="saleSeller", targetEntity=InvoiceTrans.class)
    private List<InvoiceTrans> listOfInvoiceTrans;

    @OneToMany(mappedBy="saleSeller", targetEntity=Contact.class)
    private List<Contact> listOfContact;

    @OneToMany(mappedBy="saleSeller", targetEntity=OrderTransDetail.class)
    private List<OrderTransDetail> listOfOrderTransDetail;

    @OneToMany(mappedBy="saleSeller", targetEntity=OrderTrans.class)
    private List<OrderTrans> listOfOrderTrans;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------



    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }




    //--- DATABASE MAPPING : prim_rate ( DOUBLE ) 
    public void setPrimRate( Double primRate ) {
        this.primRate = primRate;
    }
    public Double getPrimRate() {
        return this.primRate;
    }




    //--- DATABASE MAPPING : insert_by ( VARCHAR ) 
    public void setInsertBy( String insertBy ) {
        this.insertBy = insertBy;
    }
    public String getInsertBy() {
        return this.insertBy;
    }




    //--- DATABASE MAPPING : insert_at ( DATETIME ) 
    public void setInsertAt( Date insertAt ) {
        this.insertAt = insertAt;
    }
    public Date getInsertAt() {
        return this.insertAt;
    }




    //--- DATABASE MAPPING : update_by ( VARCHAR ) 
    public void setUpdateBy( String updateBy ) {
        this.updateBy = updateBy;
    }
    public String getUpdateBy() {
        return this.updateBy;
    }




    //--- DATABASE MAPPING : update_at ( DATETIME ) 
    public void setUpdateAt( Date updateAt ) {
        this.updateAt = updateAt;
    }
    public Date getUpdateAt() {
        return this.updateAt;
    }




    //--- DATABASE MAPPING : is_active ( BIT ) 
    public void setIsActive( Boolean isActive ) {
        this.isActive = isActive;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }




    //--- DATABASE MAPPING : workspace ( INT ) 
    public void setWorkspace( Integer workspace ) {
        this.workspace = workspace;
    }
    public Integer getWorkspace() {
        return this.workspace;
    }





    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfStockTransDetail( List<StockTransDetail> listOfStockTransDetail ) {
        this.listOfStockTransDetail = listOfStockTransDetail;
    }
    public List<StockTransDetail> getListOfStockTransDetail() {
        return this.listOfStockTransDetail;
    }

    public void setListOfStockTrans( List<StockTrans> listOfStockTrans ) {
        this.listOfStockTrans = listOfStockTrans;
    }
    public List<StockTrans> getListOfStockTrans() {
        return this.listOfStockTrans;
    }

    public void setListOfWaybillTrans( List<WaybillTrans> listOfWaybillTrans ) {
        this.listOfWaybillTrans = listOfWaybillTrans;
    }
    public List<WaybillTrans> getListOfWaybillTrans() {
        return this.listOfWaybillTrans;
    }

    public void setListOfInvoiceTransDetail( List<InvoiceTransDetail> listOfInvoiceTransDetail ) {
        this.listOfInvoiceTransDetail = listOfInvoiceTransDetail;
    }
    public List<InvoiceTransDetail> getListOfInvoiceTransDetail() {
        return this.listOfInvoiceTransDetail;
    }

    public void setListOfWaybillTransDetail( List<WaybillTransDetail> listOfWaybillTransDetail ) {
        this.listOfWaybillTransDetail = listOfWaybillTransDetail;
    }
    public List<WaybillTransDetail> getListOfWaybillTransDetail() {
        return this.listOfWaybillTransDetail;
    }

    public void setListOfInvoiceTrans( List<InvoiceTrans> listOfInvoiceTrans ) {
        this.listOfInvoiceTrans = listOfInvoiceTrans;
    }
    public List<InvoiceTrans> getListOfInvoiceTrans() {
        return this.listOfInvoiceTrans;
    }

    public void setListOfContact( List<Contact> listOfContact ) {
        this.listOfContact = listOfContact;
    }
    public List<Contact> getListOfContact() {
        return this.listOfContact;
    }

    public void setListOfOrderTransDetail( List<OrderTransDetail> listOfOrderTransDetail ) {
        this.listOfOrderTransDetail = listOfOrderTransDetail;
    }
    public List<OrderTransDetail> getListOfOrderTransDetail() {
        return this.listOfOrderTransDetail;
    }

    public void setListOfOrderTrans( List<OrderTrans> listOfOrderTrans ) {
        this.listOfOrderTrans = listOfOrderTrans;
    }
    public List<OrderTrans> getListOfOrderTrans() {
        return this.listOfOrderTrans;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(primRate);
        sb.append("|");
        sb.append(insertBy);
        sb.append("|");
        sb.append(insertAt);
        sb.append("|");
        sb.append(updateBy);
        sb.append("|");
        sb.append(updateAt);
        sb.append("|");
        sb.append(isActive);
        sb.append("|");
        sb.append(workspace);
        sb.append("|");
        sb.append(version);
        return sb.toString(); 
    } 

}
