/*
 * Created on 7 Mar 2016 ( Time 11:05:23 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

import org.hibernate.envers.Audited;

/**
 * Persistent class for entity stored in table "stock_extra_fields"
 *
 * @author Telosys Tools Generator
 *
 */




@Audited
@Entity
// Define named queries here
@Table(name = "stock_extra_fields")
@org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class StockExtraFields extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
//	@EmbeddedId
//   private StockExtraFieldsKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="name", nullable=false, length=30)
    private String     name         ;    @Column(name="insert_by", length=20)
    private String     insertBy     ;    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="insert_at")
    private Date       insertAt     ;    @Column(name="update_by", length=20)
    private String     updateBy     ;    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_at")
    private Date       updateAt     ;    @Column(name="is_active")
    private Boolean    isActive     ;    @Column(name="extra_fields_id")
    private Integer    extraFieldsId ;    @Column(name="workspace", nullable=false)
    private Integer    workspace    ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="stockExtraFields", targetEntity=Stock.class)
    private List<Stock> listOfStock ;

    @OneToMany(mappedBy="stockExtraFields3", targetEntity=StockCosting.class)
    private List<StockCosting> listOfStockCosting3;

    @OneToMany(mappedBy="stockExtraFields10", targetEntity=Stock.class)
    private List<Stock> listOfStock10;

    @OneToMany(mappedBy="stockExtraFields9", targetEntity=SaleCampaign.class)
    private List<SaleCampaign> listOfSaleCampaign9;

    @OneToMany(mappedBy="stockExtraFields3", targetEntity=StockPriceList.class)
    private List<StockPriceList> listOfStockPriceList3;

    @OneToMany(mappedBy="stockExtraFields", targetEntity=SaleCampaign.class)
    private List<SaleCampaign> listOfSaleCampaign;

    @OneToMany(mappedBy="stockExtraFields6", targetEntity=StockPriceUpdate.class)
    private List<StockPriceUpdate> listOfStockPriceUpdate6;

    @OneToMany(mappedBy="stockExtraFields2", targetEntity=StockPriceList.class)
    private List<StockPriceList> listOfStockPriceList2;

    @OneToMany(mappedBy="stockExtraFields2", targetEntity=StockCosting.class)
    private List<StockCosting> listOfStockCosting2;

    @OneToMany(mappedBy="stockExtraFields9", targetEntity=Stock.class)
    private List<Stock> listOfStock9;

    @OneToMany(mappedBy="stockExtraFields8", targetEntity=SaleCampaign.class)
    private List<SaleCampaign> listOfSaleCampaign8;

    @OneToMany(mappedBy="stockExtraFields5", targetEntity=StockPriceUpdate.class)
    private List<StockPriceUpdate> listOfStockPriceUpdate5;

    @OneToMany(mappedBy="stockExtraFields10", targetEntity=StockPriceList.class)
    private List<StockPriceList> listOfStockPriceList10;

    @OneToMany(mappedBy="stockExtraFields", targetEntity=StockPriceList.class)
    private List<StockPriceList> listOfStockPriceList;

    @OneToMany(mappedBy="stockExtraFields10", targetEntity=StockCosting.class)
    private List<StockCosting> listOfStockCosting10;

    @OneToMany(mappedBy="stockExtraFields", targetEntity=StockCosting.class)
    private List<StockCosting> listOfStockCosting;

    @OneToMany(mappedBy="stockExtraFields8", targetEntity=Stock.class)
    private List<Stock> listOfStock8;

    @OneToMany(mappedBy="stockExtraFields7", targetEntity=SaleCampaign.class)
    private List<SaleCampaign> listOfSaleCampaign7;

    @OneToMany(mappedBy="stockExtraFields4", targetEntity=StockPriceUpdate.class)
    private List<StockPriceUpdate> listOfStockPriceUpdate4;

    @OneToMany(mappedBy="stockExtraFields9", targetEntity=StockPriceList.class)
    private List<StockPriceList> listOfStockPriceList9;

    @OneToMany(mappedBy="stockExtraFields9", targetEntity=StockCosting.class)
    private List<StockCosting> listOfStockCosting9;

    @OneToMany(mappedBy="stockExtraFields7", targetEntity=Stock.class)
    private List<Stock> listOfStock7;

    @OneToMany(mappedBy="stockExtraFields6", targetEntity=SaleCampaign.class)
    private List<SaleCampaign> listOfSaleCampaign6;

    @OneToMany(mappedBy="stockExtraFields3", targetEntity=StockPriceUpdate.class)
    private List<StockPriceUpdate> listOfStockPriceUpdate3;

    @OneToMany(mappedBy="stockExtraFields8", targetEntity=StockPriceList.class)
    private List<StockPriceList> listOfStockPriceList8;

    @OneToMany(mappedBy="stockExtraFields8", targetEntity=StockCosting.class)
    private List<StockCosting> listOfStockCosting8;

    @OneToMany(mappedBy="stockExtraFields6", targetEntity=Stock.class)
    private List<Stock> listOfStock6;

    @OneToMany(mappedBy="stockExtraFields5", targetEntity=SaleCampaign.class)
    private List<SaleCampaign> listOfSaleCampaign5;

    @OneToMany(mappedBy="stockExtraFields7", targetEntity=StockPriceList.class)
    private List<StockPriceList> listOfStockPriceList7;

    @OneToMany(mappedBy="stockExtraFields7", targetEntity=StockCosting.class)
    private List<StockCosting> listOfStockCosting7;

    @OneToMany(mappedBy="stockExtraFields5", targetEntity=Stock.class)
    private List<Stock> listOfStock5;

    @OneToMany(mappedBy="stockExtraFields4", targetEntity=SaleCampaign.class)
    private List<SaleCampaign> listOfSaleCampaign4;

    @OneToMany(mappedBy="stockExtraFields10", targetEntity=StockPriceUpdate.class)
    private List<StockPriceUpdate> listOfStockPriceUpdate10;

    @OneToMany(mappedBy="stockExtraFields6", targetEntity=StockPriceList.class)
    private List<StockPriceList> listOfStockPriceList6;

    @OneToMany(mappedBy="stockExtraFields2", targetEntity=StockPriceUpdate.class)
    private List<StockPriceUpdate> listOfStockPriceUpdate2;

    @OneToMany(mappedBy="stockExtraFields6", targetEntity=StockCosting.class)
    private List<StockCosting> listOfStockCosting6;

    @OneToMany(mappedBy="stockExtraFields4", targetEntity=Stock.class)
    private List<Stock> listOfStock4;

    @OneToMany(mappedBy="stockExtraFields3", targetEntity=SaleCampaign.class)
    private List<SaleCampaign> listOfSaleCampaign3;

    @OneToMany(mappedBy="stockExtraFields9", targetEntity=StockPriceUpdate.class)
    private List<StockPriceUpdate> listOfStockPriceUpdate9;

    @OneToMany(mappedBy="stockExtraFields5", targetEntity=StockCosting.class)
    private List<StockCosting> listOfStockCosting5;

    @OneToMany(mappedBy="stockExtraFields5", targetEntity=StockPriceList.class)
    private List<StockPriceList> listOfStockPriceList5;

    @OneToMany(mappedBy="stockExtraFields", targetEntity=StockPriceUpdate.class)
    private List<StockPriceUpdate> listOfStockPriceUpdate;

    @OneToMany(mappedBy="stockExtraFields3", targetEntity=Stock.class)
    private List<Stock> listOfStock3;

    @OneToMany(mappedBy="stockExtraFields8", targetEntity=StockPriceUpdate.class)
    private List<StockPriceUpdate> listOfStockPriceUpdate8;

    @OneToMany(mappedBy="stockExtraFields2", targetEntity=Stock.class)
    private List<Stock> listOfStock2;

    @OneToMany(mappedBy="stockExtraFields4", targetEntity=StockCosting.class)
    private List<StockCosting> listOfStockCosting4;

    @OneToMany(mappedBy="stockExtraFields10", targetEntity=SaleCampaign.class)
    private List<SaleCampaign> listOfSaleCampaign10;

    @OneToMany(mappedBy="stockExtraFields4", targetEntity=StockPriceList.class)
    private List<StockPriceList> listOfStockPriceList4;

    @OneToMany(mappedBy="stockExtraFields2", targetEntity=SaleCampaign.class)
    private List<SaleCampaign> listOfSaleCampaign2;

    @OneToMany(mappedBy="stockExtraFields7", targetEntity=StockPriceUpdate.class)
    private List<StockPriceUpdate> listOfStockPriceUpdate7;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------



    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }




    //--- DATABASE MAPPING : insert_by ( VARCHAR ) 
    public void setInsertBy( String insertBy ) {
        this.insertBy = insertBy;
    }
    public String getInsertBy() {
        return this.insertBy;
    }




    //--- DATABASE MAPPING : insert_at ( DATETIME ) 
    public void setInsertAt( Date insertAt ) {
        this.insertAt = insertAt;
    }
    public Date getInsertAt() {
        return this.insertAt;
    }




    //--- DATABASE MAPPING : update_by ( VARCHAR ) 
    public void setUpdateBy( String updateBy ) {
        this.updateBy = updateBy;
    }
    public String getUpdateBy() {
        return this.updateBy;
    }




    //--- DATABASE MAPPING : update_at ( DATETIME ) 
    public void setUpdateAt( Date updateAt ) {
        this.updateAt = updateAt;
    }
    public Date getUpdateAt() {
        return this.updateAt;
    }




    //--- DATABASE MAPPING : is_active ( BIT ) 
    public void setIsActive( Boolean isActive ) {
        this.isActive = isActive;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }




    //--- DATABASE MAPPING : extra_fields_id ( INT ) 
    public void setExtraFieldsId( Integer extraFieldsId ) {
        this.extraFieldsId = extraFieldsId;
    }
    public Integer getExtraFieldsId() {
        return this.extraFieldsId;
    }




    //--- DATABASE MAPPING : workspace ( INT ) 
    public void setWorkspace( Integer workspace ) {
        this.workspace = workspace;
    }
    public Integer getWorkspace() {
        return this.workspace;
    }





    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfStock( List<Stock> listOfStock ) {
        this.listOfStock = listOfStock;
    }
    public List<Stock> getListOfStock() {
        return this.listOfStock;
    }

    public void setListOfStockCosting3( List<StockCosting> listOfStockCosting3 ) {
        this.listOfStockCosting3 = listOfStockCosting3;
    }
    public List<StockCosting> getListOfStockCosting3() {
        return this.listOfStockCosting3;
    }

    public void setListOfStock10( List<Stock> listOfStock10 ) {
        this.listOfStock10 = listOfStock10;
    }
    public List<Stock> getListOfStock10() {
        return this.listOfStock10;
    }

    public void setListOfSaleCampaign9( List<SaleCampaign> listOfSaleCampaign9 ) {
        this.listOfSaleCampaign9 = listOfSaleCampaign9;
    }
    public List<SaleCampaign> getListOfSaleCampaign9() {
        return this.listOfSaleCampaign9;
    }

    public void setListOfStockPriceList3( List<StockPriceList> listOfStockPriceList3 ) {
        this.listOfStockPriceList3 = listOfStockPriceList3;
    }
    public List<StockPriceList> getListOfStockPriceList3() {
        return this.listOfStockPriceList3;
    }

    public void setListOfSaleCampaign( List<SaleCampaign> listOfSaleCampaign ) {
        this.listOfSaleCampaign = listOfSaleCampaign;
    }
    public List<SaleCampaign> getListOfSaleCampaign() {
        return this.listOfSaleCampaign;
    }

    public void setListOfStockPriceUpdate6( List<StockPriceUpdate> listOfStockPriceUpdate6 ) {
        this.listOfStockPriceUpdate6 = listOfStockPriceUpdate6;
    }
    public List<StockPriceUpdate> getListOfStockPriceUpdate6() {
        return this.listOfStockPriceUpdate6;
    }

    public void setListOfStockPriceList2( List<StockPriceList> listOfStockPriceList2 ) {
        this.listOfStockPriceList2 = listOfStockPriceList2;
    }
    public List<StockPriceList> getListOfStockPriceList2() {
        return this.listOfStockPriceList2;
    }

    public void setListOfStockCosting2( List<StockCosting> listOfStockCosting2 ) {
        this.listOfStockCosting2 = listOfStockCosting2;
    }
    public List<StockCosting> getListOfStockCosting2() {
        return this.listOfStockCosting2;
    }

    public void setListOfStock9( List<Stock> listOfStock9 ) {
        this.listOfStock9 = listOfStock9;
    }
    public List<Stock> getListOfStock9() {
        return this.listOfStock9;
    }

    public void setListOfSaleCampaign8( List<SaleCampaign> listOfSaleCampaign8 ) {
        this.listOfSaleCampaign8 = listOfSaleCampaign8;
    }
    public List<SaleCampaign> getListOfSaleCampaign8() {
        return this.listOfSaleCampaign8;
    }

    public void setListOfStockPriceUpdate5( List<StockPriceUpdate> listOfStockPriceUpdate5 ) {
        this.listOfStockPriceUpdate5 = listOfStockPriceUpdate5;
    }
    public List<StockPriceUpdate> getListOfStockPriceUpdate5() {
        return this.listOfStockPriceUpdate5;
    }

    public void setListOfStockPriceList10( List<StockPriceList> listOfStockPriceList10 ) {
        this.listOfStockPriceList10 = listOfStockPriceList10;
    }
    public List<StockPriceList> getListOfStockPriceList10() {
        return this.listOfStockPriceList10;
    }

    public void setListOfStockPriceList( List<StockPriceList> listOfStockPriceList ) {
        this.listOfStockPriceList = listOfStockPriceList;
    }
    public List<StockPriceList> getListOfStockPriceList() {
        return this.listOfStockPriceList;
    }

    public void setListOfStockCosting10( List<StockCosting> listOfStockCosting10 ) {
        this.listOfStockCosting10 = listOfStockCosting10;
    }
    public List<StockCosting> getListOfStockCosting10() {
        return this.listOfStockCosting10;
    }

    public void setListOfStockCosting( List<StockCosting> listOfStockCosting ) {
        this.listOfStockCosting = listOfStockCosting;
    }
    public List<StockCosting> getListOfStockCosting() {
        return this.listOfStockCosting;
    }

    public void setListOfStock8( List<Stock> listOfStock8 ) {
        this.listOfStock8 = listOfStock8;
    }
    public List<Stock> getListOfStock8() {
        return this.listOfStock8;
    }

    public void setListOfSaleCampaign7( List<SaleCampaign> listOfSaleCampaign7 ) {
        this.listOfSaleCampaign7 = listOfSaleCampaign7;
    }
    public List<SaleCampaign> getListOfSaleCampaign7() {
        return this.listOfSaleCampaign7;
    }

    public void setListOfStockPriceUpdate4( List<StockPriceUpdate> listOfStockPriceUpdate4 ) {
        this.listOfStockPriceUpdate4 = listOfStockPriceUpdate4;
    }
    public List<StockPriceUpdate> getListOfStockPriceUpdate4() {
        return this.listOfStockPriceUpdate4;
    }

    public void setListOfStockPriceList9( List<StockPriceList> listOfStockPriceList9 ) {
        this.listOfStockPriceList9 = listOfStockPriceList9;
    }
    public List<StockPriceList> getListOfStockPriceList9() {
        return this.listOfStockPriceList9;
    }

    public void setListOfStockCosting9( List<StockCosting> listOfStockCosting9 ) {
        this.listOfStockCosting9 = listOfStockCosting9;
    }
    public List<StockCosting> getListOfStockCosting9() {
        return this.listOfStockCosting9;
    }

    public void setListOfStock7( List<Stock> listOfStock7 ) {
        this.listOfStock7 = listOfStock7;
    }
    public List<Stock> getListOfStock7() {
        return this.listOfStock7;
    }

    public void setListOfSaleCampaign6( List<SaleCampaign> listOfSaleCampaign6 ) {
        this.listOfSaleCampaign6 = listOfSaleCampaign6;
    }
    public List<SaleCampaign> getListOfSaleCampaign6() {
        return this.listOfSaleCampaign6;
    }

    public void setListOfStockPriceUpdate3( List<StockPriceUpdate> listOfStockPriceUpdate3 ) {
        this.listOfStockPriceUpdate3 = listOfStockPriceUpdate3;
    }
    public List<StockPriceUpdate> getListOfStockPriceUpdate3() {
        return this.listOfStockPriceUpdate3;
    }

    public void setListOfStockPriceList8( List<StockPriceList> listOfStockPriceList8 ) {
        this.listOfStockPriceList8 = listOfStockPriceList8;
    }
    public List<StockPriceList> getListOfStockPriceList8() {
        return this.listOfStockPriceList8;
    }

    public void setListOfStockCosting8( List<StockCosting> listOfStockCosting8 ) {
        this.listOfStockCosting8 = listOfStockCosting8;
    }
    public List<StockCosting> getListOfStockCosting8() {
        return this.listOfStockCosting8;
    }

    public void setListOfStock6( List<Stock> listOfStock6 ) {
        this.listOfStock6 = listOfStock6;
    }
    public List<Stock> getListOfStock6() {
        return this.listOfStock6;
    }

    public void setListOfSaleCampaign5( List<SaleCampaign> listOfSaleCampaign5 ) {
        this.listOfSaleCampaign5 = listOfSaleCampaign5;
    }
    public List<SaleCampaign> getListOfSaleCampaign5() {
        return this.listOfSaleCampaign5;
    }

    public void setListOfStockPriceList7( List<StockPriceList> listOfStockPriceList7 ) {
        this.listOfStockPriceList7 = listOfStockPriceList7;
    }
    public List<StockPriceList> getListOfStockPriceList7() {
        return this.listOfStockPriceList7;
    }

    public void setListOfStockCosting7( List<StockCosting> listOfStockCosting7 ) {
        this.listOfStockCosting7 = listOfStockCosting7;
    }
    public List<StockCosting> getListOfStockCosting7() {
        return this.listOfStockCosting7;
    }

    public void setListOfStock5( List<Stock> listOfStock5 ) {
        this.listOfStock5 = listOfStock5;
    }
    public List<Stock> getListOfStock5() {
        return this.listOfStock5;
    }

    public void setListOfSaleCampaign4( List<SaleCampaign> listOfSaleCampaign4 ) {
        this.listOfSaleCampaign4 = listOfSaleCampaign4;
    }
    public List<SaleCampaign> getListOfSaleCampaign4() {
        return this.listOfSaleCampaign4;
    }

    public void setListOfStockPriceUpdate10( List<StockPriceUpdate> listOfStockPriceUpdate10 ) {
        this.listOfStockPriceUpdate10 = listOfStockPriceUpdate10;
    }
    public List<StockPriceUpdate> getListOfStockPriceUpdate10() {
        return this.listOfStockPriceUpdate10;
    }

    public void setListOfStockPriceList6( List<StockPriceList> listOfStockPriceList6 ) {
        this.listOfStockPriceList6 = listOfStockPriceList6;
    }
    public List<StockPriceList> getListOfStockPriceList6() {
        return this.listOfStockPriceList6;
    }

    public void setListOfStockPriceUpdate2( List<StockPriceUpdate> listOfStockPriceUpdate2 ) {
        this.listOfStockPriceUpdate2 = listOfStockPriceUpdate2;
    }
    public List<StockPriceUpdate> getListOfStockPriceUpdate2() {
        return this.listOfStockPriceUpdate2;
    }

    public void setListOfStockCosting6( List<StockCosting> listOfStockCosting6 ) {
        this.listOfStockCosting6 = listOfStockCosting6;
    }
    public List<StockCosting> getListOfStockCosting6() {
        return this.listOfStockCosting6;
    }

    public void setListOfStock4( List<Stock> listOfStock4 ) {
        this.listOfStock4 = listOfStock4;
    }
    public List<Stock> getListOfStock4() {
        return this.listOfStock4;
    }

    public void setListOfSaleCampaign3( List<SaleCampaign> listOfSaleCampaign3 ) {
        this.listOfSaleCampaign3 = listOfSaleCampaign3;
    }
    public List<SaleCampaign> getListOfSaleCampaign3() {
        return this.listOfSaleCampaign3;
    }

    public void setListOfStockPriceUpdate9( List<StockPriceUpdate> listOfStockPriceUpdate9 ) {
        this.listOfStockPriceUpdate9 = listOfStockPriceUpdate9;
    }
    public List<StockPriceUpdate> getListOfStockPriceUpdate9() {
        return this.listOfStockPriceUpdate9;
    }

    public void setListOfStockCosting5( List<StockCosting> listOfStockCosting5 ) {
        this.listOfStockCosting5 = listOfStockCosting5;
    }
    public List<StockCosting> getListOfStockCosting5() {
        return this.listOfStockCosting5;
    }

    public void setListOfStockPriceList5( List<StockPriceList> listOfStockPriceList5 ) {
        this.listOfStockPriceList5 = listOfStockPriceList5;
    }
    public List<StockPriceList> getListOfStockPriceList5() {
        return this.listOfStockPriceList5;
    }

    public void setListOfStockPriceUpdate( List<StockPriceUpdate> listOfStockPriceUpdate ) {
        this.listOfStockPriceUpdate = listOfStockPriceUpdate;
    }
    public List<StockPriceUpdate> getListOfStockPriceUpdate() {
        return this.listOfStockPriceUpdate;
    }

    public void setListOfStock3( List<Stock> listOfStock3 ) {
        this.listOfStock3 = listOfStock3;
    }
    public List<Stock> getListOfStock3() {
        return this.listOfStock3;
    }

    public void setListOfStockPriceUpdate8( List<StockPriceUpdate> listOfStockPriceUpdate8 ) {
        this.listOfStockPriceUpdate8 = listOfStockPriceUpdate8;
    }
    public List<StockPriceUpdate> getListOfStockPriceUpdate8() {
        return this.listOfStockPriceUpdate8;
    }

    public void setListOfStock2( List<Stock> listOfStock2 ) {
        this.listOfStock2 = listOfStock2;
    }
    public List<Stock> getListOfStock2() {
        return this.listOfStock2;
    }

    public void setListOfStockCosting4( List<StockCosting> listOfStockCosting4 ) {
        this.listOfStockCosting4 = listOfStockCosting4;
    }
    public List<StockCosting> getListOfStockCosting4() {
        return this.listOfStockCosting4;
    }

    public void setListOfSaleCampaign10( List<SaleCampaign> listOfSaleCampaign10 ) {
        this.listOfSaleCampaign10 = listOfSaleCampaign10;
    }
    public List<SaleCampaign> getListOfSaleCampaign10() {
        return this.listOfSaleCampaign10;
    }

    public void setListOfStockPriceList4( List<StockPriceList> listOfStockPriceList4 ) {
        this.listOfStockPriceList4 = listOfStockPriceList4;
    }
    public List<StockPriceList> getListOfStockPriceList4() {
        return this.listOfStockPriceList4;
    }

    public void setListOfSaleCampaign2( List<SaleCampaign> listOfSaleCampaign2 ) {
        this.listOfSaleCampaign2 = listOfSaleCampaign2;
    }
    public List<SaleCampaign> getListOfSaleCampaign2() {
        return this.listOfSaleCampaign2;
    }

    public void setListOfStockPriceUpdate7( List<StockPriceUpdate> listOfStockPriceUpdate7 ) {
        this.listOfStockPriceUpdate7 = listOfStockPriceUpdate7;
    }
    public List<StockPriceUpdate> getListOfStockPriceUpdate7() {
        return this.listOfStockPriceUpdate7;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(name);
        sb.append("|");
        sb.append(insertBy);
        sb.append("|");
        sb.append(insertAt);
        sb.append("|");
        sb.append(updateBy);
        sb.append("|");
        sb.append(updateAt);
        sb.append("|");
        sb.append(isActive);
        sb.append("|");
        sb.append(extraFieldsId);
        sb.append("|");
        sb.append(workspace);
        sb.append("|");
        sb.append(version);
        return sb.toString(); 
    } 

}
