/*
 * Created on 7 Mar 2016 ( Time 11:05:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

import org.hibernate.envers.Audited;

/**
 * Persistent class for entity stored in table "stock_trans_factor"
 *
 * @author Telosys Tools Generator
 *
 */




@Audited
@Entity
// Define named queries here
@Table(name = "stock_trans_factor")
@org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class StockTransFactor extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
//	@EmbeddedId
//   private StockTransFactorKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="effect")
    private Double     effect       ;    @Column(name="quantity")
    private Double     quantity     ;    @Column(name="amount")
    private Double     amount       ;
	// "transId" (column "trans_id") is not defined by itself because used as FK in a link 
	// "factorId" (column "factor_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="factor_id", referencedColumnName="id")
    private StockCostFactor stockCostFactor;

    @ManyToOne
    @JoinColumn(name="trans_id", referencedColumnName="id")
    private StockTrans stockTrans  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------



    //--- DATABASE MAPPING : effect ( DOUBLE ) 
    public void setEffect( Double effect ) {
        this.effect = effect;
    }
    public Double getEffect() {
        return this.effect;
    }




    //--- DATABASE MAPPING : quantity ( DOUBLE ) 
    public void setQuantity( Double quantity ) {
        this.quantity = quantity;
    }
    public Double getQuantity() {
        return this.quantity;
    }




    //--- DATABASE MAPPING : amount ( DOUBLE ) 
    public void setAmount( Double amount ) {
        this.amount = amount;
    }
    public Double getAmount() {
        return this.amount;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setStockCostFactor( StockCostFactor stockCostFactor ) {
        this.stockCostFactor = stockCostFactor;
    }
    public StockCostFactor getStockCostFactor() {
        return this.stockCostFactor;
    }

    public void setStockTrans( StockTrans stockTrans ) {
        this.stockTrans = stockTrans;
    }
    public StockTrans getStockTrans() {
        return this.stockTrans;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(effect);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(amount);
        return sb.toString(); 
    } 

}
