/*
 * Created on 7 Mar 2016 ( Time 11:05:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

import org.hibernate.envers.Audited;

/**
 * Persistent class for entity stored in table "waybill_trans_status_history"
 *
 * @author Telosys Tools Generator
 *
 */




@Audited
@Entity
// Define named queries here
@Table(name = "waybill_trans_status_history")
@org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class WaybillTransStatusHistory extends BaseEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
//	@EmbeddedId
//   private WaybillTransStatusHistoryKey compositePrimaryKey ;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="trans_time")
    private Date       transTime    ;    @Column(name="trans_id", nullable=false)
    private Integer    transId      ;    @Column(name="status_id", nullable=false)
    private Integer    statusId     ;    @Column(name="username", length=20)
    private String     username     ;    @Column(name="description", length=150)
    private String     description  ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------



    //--- DATABASE MAPPING : trans_time ( DATETIME ) 
    public void setTransTime( Date transTime ) {
        this.transTime = transTime;
    }
    public Date getTransTime() {
        return this.transTime;
    }




    //--- DATABASE MAPPING : trans_id ( INT ) 
    public void setTransId( Integer transId ) {
        this.transId = transId;
    }
    public Integer getTransId() {
        return this.transId;
    }




    //--- DATABASE MAPPING : status_id ( INT ) 
    public void setStatusId( Integer statusId ) {
        this.statusId = statusId;
    }
    public Integer getStatusId() {
        return this.statusId;
    }




    //--- DATABASE MAPPING : username ( VARCHAR ) 
    public void setUsername( String username ) {
        this.username = username;
    }
    public String getUsername() {
        return this.username;
    }




    //--- DATABASE MAPPING : description ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(transTime);
        sb.append("|");
        sb.append(transId);
        sb.append("|");
        sb.append(statusId);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(description);
        return sb.toString(); 
    } 

}
